// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gfoogchxvxjfqwulgrbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmb29nY2h4dnhqZnF3dWxncmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NTg3ODIsImV4cCI6MjA3NzIzNDc4Mn0.ZERsAMY-0EZ2jWg3j2gnhM6-sYIgEouWRYkKSW9LT8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);