name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Dispara o workflow quando houver push na branch 'main'

# Adiciona permissões de escrita para o GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Removendo a configuração de cache para evitar o erro de lock file ausente
          # cache: 'npm' 

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # A pasta que contém os arquivos estáticos
          publish_branch: gh-pages # A branch que o GitHub Pages deve usar para servir o conteúdo
          cname: # Deixe vazio se não estiver usando domínio customizado